load("@rules_java//java:defs.bzl", "java_binary")

# java_library(
#     name = "protobufbin",
#     srcs = glob(["*.java"], exclude=["*Main.java"]),
#     deps = [
#     ],
# )


java_binary(
    name = "EditorMain",
    srcs = ["EditorMain.java"],
    main_class = "net.ianoc.protobufbin.EditorMain",
    deps = [
    ],
)
